---
# Install đặt cơ bản cho tất cả các node
- name: Install common
  hosts: all
  become: yes
  roles:
    - common

# Install ZooKeeper
- name: Install ZooKeeper
  hosts: zookeeper
  become: yes
  roles:
    - zookeeper

# Install JournalNode
- name: Install JournalNode
  hosts: journalnode
  become: yes
  roles:
    - journalnode

# Install NameNode
- name: Install NameNode
  hosts: namenode
  become: yes
  roles:
    - namenode

# Install DataNode
- name: Install DataNode
  hosts: datanode
  become: yes
  roles:
    - datanode

# Install HBase Master
- name: Install HBase Master
  hosts: hbase_master
  become: yes
  roles:
    - hbase_master

# Install HBase RegionServer
- name: Install HBase RegionServer
  hosts: hbase_regionserver
  become: yes
  roles:
    - hbase_regionserver