---
- name: Download HBase
  get_url:
    url: https://downloads.apache.org/hbase/2.5.15/hbase-2.5.15-hadoop3-bin.tar.gz
    dest: /tmp/hbase.tar.gz

- name: Extract HBase
  unarchive:
    src: /tmp/hbase.tar.gz
    dest: /opt/
    remote_src: yes

- name: Rename extracted folder to hbase
  command: mv /opt/hbase-2.5.15-hadoop3 /opt/hbase
  args:
    creates: /opt/hbase

- name: Copy hbase-site.xml
  copy:
    src: hbase-site.xml
    dest: /opt/hbase/conf/hbase-site.xml

- name: Start HRegionServer
  shell: /opt/hbase/bin/hbase-daemon.sh start regionserver
  when: is_regionserver