---
- name: Download HBase
  get_url:
    url: https://downloads.apache.org/hbase/2.5.15/hbase-2.5.15-hadoop3-bin.tar.gz
    dest: /tmp/hbase.tar.gz

- name: Extract HBase
  unarchive:
    src: /tmp/hbase.tar.gz
    dest: /opt/
    remote_src: yes

- name: Rename extracted folder to hbase
  command: mv /opt/hbase-2.5.15-hadoop3 /opt/hbase
  args:
    creates: /opt/hbase

- name: Copy hbase-site.xml
  template:
    src: hbase-site.xml.j2
    dest: /opt/hbase/conf/hbase-site.xml

- name: Copy core-site.xml vào HBase
  template:
    src: core-site.xml.j2
    dest: /opt/hbase/conf/core-site.xml

- name: Copy hdfs-site.xml vào HBase
  template:
    src: hdfs-site.xml.j2
    dest: /opt/hbase/conf/hdfs-site.xml

- name: Start HRegionServer
  shell: /opt/hbase/bin/hbase-daemon.sh start regionserver
  register: regionserver_start
  failed_when: regionserver_start.rc != 0 and "already running" not in regionserver_start.stdout