---
- name: Download HBase
  get_url:
    url: https://downloads.apache.org/hbase/2.5.15/hbase-2.5.15-hadoop3-bin.tar.gz
    dest: /tmp/hbase.tar.gz

- name: Extract HBase
  unarchive:
    src: /tmp/hbase.tar.gz
    dest: /opt/
    remote_src: yes

- name: Rename extracted folder to hbase
  command: mv /opt/hbase-2.5.15-hadoop3 /opt/hbase
  args:
    creates: /opt/hbase

- name: Copy core-site.xml vào HBase
  template:
    src: core-site.xml.j2
    dest: /opt/hbase/conf/core-site.xml

- name: Copy hdfs-site.xml vào HBase
  template:
    src: hdfs-site.xml.j2
    dest: /opt/hbase/conf/hdfs-site.xml

- name: Start HMaster
  shell: /opt/hbase/bin/hbase-daemon.sh start master
  register: master_start
  failed_when: master_start.rc != 0 and "running as process" not in master_start.stdout