---
- import_tasks: test1.yml
  tags: [test1, namenode_failover]

- import_tasks: test2.yml
  tags: [test2, zkfc_failover]

- import_tasks: test3.yml
  tags: [test3, journalnode_quorum]

- import_tasks: test4.yml
  tags: [test4, zookeeper_quorum]

- import_tasks: test5.yml
  tags: [test5, hmaster_failover]

- import_tasks: test6.yml
  tags: [test6, rs_dn_failure]