---
- name: Download ZooKeeper
  get_url:
    url: https://downloads.apache.org/zookeeper/zookeeper-3.8.6/apache-zookeeper-3.8.6-bin.tar.gz
    dest: /tmp/zookeeper.tar.gz

- name: Extract ZooKeeper
  unarchive:
    src: /tmp/zookeeper.tar.gz
    dest: /opt/
    remote_src: yes
  args:
    creates: /opt/apache-zookeeper-3.8.6-bin

- name: Rename extracted folder to hadoop
  command: mv /opt/hadoop-3.3.6 /opt/hadoop
  args:
    creates: /opt/hadoop
    
- name: Copy core-site.xml
  template:
    src: core-site.xml.j2
    dest: /opt/hadoop/etc/hadoop/core-site.xml

- name: Copy hdfs-site.xml
  template:
    src: hdfs-site.xml.j2
    dest: /opt/hadoop/etc/hadoop/hdfs-site.xml

- name: Start JournalNode
  shell: /opt/hadoop/bin/hdfs --daemon start journalnode
  register: jn_start
  failed_when: jn_start.rc != 0 and "is running" not in jn_start.stderr