---
- name: Download Hadoop
  get_url:
    url: https://downloads.apache.org/hadoop/common/hadoop-3.3.6/hadoop-3.3.6.tar.gz
    dest: /tmp/hadoop.tar.gz

- name: Extract Hadoop
  unarchive:
    src: /tmp/hadoop.tar.gz
    dest: /opt/
    remote_src: yes

- name: Copy core-site.xml
  template:
    src: core-site.xml.j2
    dest: /opt/hadoop/etc/hadoop/core-site.xml

- name: Copy hdfs-site.xml
  template:
    src: hdfs-site.xml.j2
    dest: /opt/hadoop/etc/hadoop/hdfs-site.xml

- name: Start JournalNode
  shell: /opt/hadoop/bin/hdfs --daemon start journalnode